
<h1>Créer un produit </h1>

<form method="POST" action="index.php?route=login">
    <fieldset>
        <label for="name">Nom produit:</label>
        <input type="text" name="name" id="name">
    </fieldset>
    <fieldset>
        <label for="image">image</label>
        <input type="file" name="image" id="image">
    </fieldset>
    <fieldset>
        <label for="description">Description</label>
        <input type="description" name="Description" id="description">
    </fieldset>
    <fieldset>
        <label for="prix">Prix</label>
        <input type="number" name="prix" id="prix">
    </fieldset>
    <fieldset>
        <input type="image" name="btn" id="btn" value="valider">
    </fieldset>
</form>