<!doctype html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Projet site e-commerce</title>
    </head>
    <body>
        <nav>
            <ul>
                <li><a href="index.php?route=login">Se connecter</a></li>
                <li><a href="index.php?route=register">Créer un compte</a></li>
                <li><a href="index.php?route=homepage">Accueil</a></li>
                <li><a href="index.php?route=edit-user">Modifier le compte</a></li>
            </ul>
        </nav>

        <?php
            require $template;
        ?>
    </body>
</html>