<h1>Créer un compte</h1>

<form method="POST" action="index.php?route=login">
    <fieldset>
        <label for="firstName">Prénom</label>
        <input type="text" name="firstName" id="firstName">
    </fieldset>
    <fieldset>
        <label for="lastName">Nom</label>
        <input type="text" name="lastName" id="lastName">
    </fieldset>
    <fieldset>
        <label for="email">Email</label>
        <input type="email" name="firsemailtName" id="email">
    </fieldset>
    <fieldset>
        <label for="password">Mot de passe</label>
        <input type="password" name="password" id="password">
    </fieldset>
    <fieldset>
        <label for="confirm-password">Confirmer le mot de passe</label>
        <input type="password" name="confirm-password" id="confirm-password">
    </fieldset>
</form>