<form>
    <fieldset>
                <legend>Modifier un utilisateur</legend>

        <div class="field">
            <label for="firstName"> Nom  : </label>
            <div class="user-first"><input type="text" id="firstName" name="first_name"></div>
        </div>
        <div class="field">
            <label for="lastName"> Prenom : </label>
            <div class="user-las"><input type="text" id="lastName" name="last_name"></div>
        </div>
         <div class="field">
            <label for="passWord"> Mot de passe : </label>
            <div class="passWord"><input type="password" id="passWord" name="password"></div>
        </div>
        
        
         <div>
            <input class="btnModify" type="submit" value="Modifier">
        </div>
  </fieldset>

</form>